### ISSUE TITLE
[0.26a] Internal server error when placing adventure backpack

### ISSUE THREAD

**Issue by stevestech** [MyEssentials/MyTown2#109]
I booted up a forge-1.7.10-10.13.2.1286 server running the following three mods:

MyTown2-1.7.10-0.26a
MyEssentials-Core-1.7.10-1.4-universal
adventurebackpack-1.7.10-0.8b

When a player places an adventure backpack on the ground inside a MyTown claimed town, he is kicked with an internal server error even if he has block place permission inside the town. In this case I was the town owner.

Here is an except from the FML server log highlighting the internal server error:
http://paste.ubuntu.com/10251006/

And here are the complete logs:
[fml-server-latest.txt](http://paste.ubuntu.com/10251038/)
[latest.txt](http://paste.ubuntu.com/10251053/)

Adding for searchability:
```
[19:12:44] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@2e9c089a:
java.lang.NullPointerException
	at mytown.protection.Protections.onBlockPlacement(Protections.java:291) ~[Protections.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_Protections_onBlockPlacement_PlaceEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) [add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) [nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[19:12:44] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[19:12:44] [Server thread/ERROR] [FML/]: 0: NORMAL
[19:12:44] [Server thread/ERROR] [FML/]: 1: ASM: mytown.protection.Protections@740b96f8 onBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[19:12:44] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
```

**Comment by nylser** [comment]
He is using non standard tileentity place code. This causes that itemInHand is null in the check and therefore, a NPE occurs.
