### ISSUE TITLE
economy class not found crash on startup with beta 1.0 or build 135

### ISSUE THREAD

**Issue by kellyschoenhofen** [MyEssentials/MyTown2#159]
Running an FTB Infinity 1.3.4 server, was on build 124, just upgraded to build 135 and the latest MyEssentials-CORE (r5 or something? 30 hours ago old) and getting the following on server startup. Downgraded to the beta 1.0 release and getting the same error. Any ideas?

[17:30:43] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[17:30:43] [Server thread/ERROR] [FML]: Caught exception from MyTown2
java.lang.NoClassDefFoundError: mytown/core/utils/economy/Economy
        at mytown.proxies.EconomyProxy.economy(EconomyProxy.java:14) ~[EconomyProxy.class:?]
        at mytown.MyTown.checkConfig(MyTown.java:199) ~[MyTown.class:?]
        at mytown.MyTown.serverStarting(MyTown.java:95) ~[MyTown.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: mytown.core.utils.economy.Economy
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
        ... 33 more
Caused by: java.lang.NullPointerException
[17:30:43] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mytown/core/utils/economy/Economy
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:740) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: mytown/core/utils/economy/Economy
        at mytown.proxies.EconomyProxy.economy(EconomyProxy.java:14) ~[EconomyProxy.class:?]
        at mytown.MyTown.checkConfig(MyTown.java:199) ~[MyTown.class:?]
        at mytown.MyTown.serverStarting(MyTown.java:95) ~[MyTown.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) ~[Loader.class:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: mytown.core.utils.economy.Economy
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
        at mytown.proxies.EconomyProxy.economy(EconomyProxy.java:14) ~[EconomyProxy.class:?]
        at mytown.MyTown.checkConfig(MyTown.java:199) ~[MyTown.class:?]
        at mytown.MyTown.serverStarting(MyTown.java:95) ~[MyTown.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) ~[Loader.class:?]
        ... 4 more
Caused by: java.lang.NullPointerException
[17:30:43] [Server thread/INFO] [FML]: Applying holder lookups
[17:30:43] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[17:30:43] [Server thread/INFO] [FML]: Holder lookups applied
[17:30:43] [pool-3-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Trasciever data saved to /home/phiro/plusone/./plusone/enderio/dimensionalTransceiver.json
[17:30:43] [Server thread/INFO] [STDOUT]: [com.mcjty.rftools.RFTools:serverStopped:185]: ###### RFTools.serverStopped
[17:30:43] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:30:43] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
Server process finished

**Comment by AfterWind** [comment]
Pretty sure you're missing MyEssentials-Core. Either that or you have a really old version of it. Download latest from here http://minecraft.curseforge.com/mc-mods/224243-myessentials-core/files

**Comment by kellyschoenhofen** [comment]
Ahha, it was a "really old" version from April 1st, I got it from here: 
https://ci.mineguild.net/job/MyEssentials-Core/

I say the -5 in the name and thought it was the 1.5r release.
