### ISSUE TITLE
NPE in mytown.protection.Protections.checkPlayer on/directly-after login

### ISSUE THREAD

**Issue by Inari-Whitebear** [MyEssentials/MyTown2#256]
java.lang.NullPointerException: Exception in server tick loop
   at mytown.protection.Protections.checkPlayer(Protections.java:170)
   at mytown.protection.Protections.worldTick(Protections.java:115)
   at cpw.mods.fml.common.eventhandler.ASMEventHandler_438_Protections_worldTick_WorldTickEvent.invoke(.dynamic)
   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
   at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:914)
   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
   at java.lang.Thread.run(Thread.java:745)

**Comment by krwminer** [comment]
Please give the full crash dump and include versions of MyTown2/Core. Thanks.

**Comment by krwminer** [comment]
It looks like the DB save of the resident failed for some reason. I fixed the code so it will not NPE in that case anymore.

**Comment by Inari-Whitebear** [comment]
Don't have the whole Log, the MyTown2 version was 1.7.10-0.1.0b though. And okay ^^
