### ISSUE TITLE
Crash at launch (opcheck?)

### ISSUE THREAD

**Issue by LameGirlyCurly** [MyEssentials/MyTown2#306]
Hi, I get a server crash with the latest 239 release combined with the MyEssentials 1.12r and MyPermissions 10-26-dev when I try to login. I've tried being both opped and non-opped.
Running KCauldron 1481 (slap me if you need more info)

28.08 02:46:49 [Server] INFO at mytown.protection.Protections.worldTick(Protections.java:118) ~[Protections.class:?]
28.08 02:46:49 [Server] INFO at mytown.protection.Protections.checkPlayer(Protections.java:169) ~[Protections.class:?]
28.08 02:46:49 [Server] INFO at mytown.entities.Town.hasPermission(Town.java:69) ~[Town.class:?]
28.08 02:46:49 [Server] INFO at mytown.entities.Town.hasPermission(Town.java:79) ~[Town.class:?]
28.08 02:46:49 [Server] INFO java.lang.NoSuchMethodError: myessentials.utils.PlayerUtils.isOp(Ljava/util/UUID;)Z
28.08 02:46:49 [Server] ERROR Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@4e2d1d90:

**Comment by LameGirlyCurly** [comment]
Fixed with using MyEssentials-Core-1.7.10-57-dev.jar from https://ci.mineguild.net/job/MyEssentials-core/
