### ISSUE TITLE
Server Startup

### ISSUE THREAD

**Issue by MrFrostmaul** [MyEssentials/MyTown2#312]
When server done starting up it immediately crashes with the following report. I have all the required mods etc. installed and running from a new install of the mods.:

Time: 31/08/15 14:34
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mytown.protection.Protection.hasPermission(Protection.java:358)
	at mytown.protection.Protection.checkEntity(Protection.java:119)
	at mytown.protection.Protections.worldTick(Protections.java:128)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_390_Protections_worldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Possibly involved mods --
Details:
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .
	MyTown 2: Version: 1.7.10-0000r. Main class: mytown.MyTown. Source: MyTown2-1.7.10-0.1.4b (1).jar. Url: .

**Comment by AfterWind** [comment]
Issue fixed already. The bugfix incoming in next update.
