### ISSUE TITLE
[0.3.0b] NPE on startup

### ISSUE THREAD

**Issue by stevestech** [MyEssentials/MyTown2#360]
When using MyTown2 0.3.0b with a Banished 1.3.0 server, I encountered a crash on startup. There was no crash-report generated, but there was a null pointer exception with stack trace in the server log which I will link here.

http://pastebin.com/DNP0MCec

```
java.lang.NullPointerException
        at mytown.config.json.RanksConfig.validate(RanksConfig.java:47) ~[RanksConfig.class:?]
        at mytown.config.json.RanksConfig.validate(RanksConfig.java:11) ~[RanksConfig.class:?]
        at myessentials.json.JsonConfig.read(JsonConfig.java:101) ~[JsonConfig.class:?]
        at mytown.config.json.RanksConfig.read(RanksConfig.java:33) ~[RanksConfig.class:?]
        at mytown.config.json.RanksConfig.read(RanksConfig.java:11) ~[RanksConfig.class:?]
        at myessentials.json.JsonConfig.init(JsonConfig.java:51) ~[JsonConfig.class:?]
        at myessentials.json.JsonConfig.init(JsonConfig.java:35) ~[JsonConfig.class:?]
        at mytown.MyTown.serverStarting(MyTown.java:83) ~[MyTown.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

I only pastebinned an excerpt, full log can be downloaded from here:
https://mega.nz/#!LcVmUISR!uzOYjbE-P76LcS2ZZSqD60Wq837tN2GHRkhCBcN-lKY

**Comment by rjdunlap** [comment]
I had a similar issue (unable to start) when starting up our server running Technodefirmacraft

**Comment by krwminer** [comment]
Retry with the latest dev MT2/MEC/MyPermissions. This might be fixed.

**Comment by groveham** [comment]
I'm having the same issue even after updating to the latest Dev versions

Log: http://pastebin.com/vZYxgyac

Using: 
MyEssentials-Core-1.7.10-88-dev
MyPermissions-1.7.10-41-dev

**Comment by krwminer** [comment]
Remove your DefaultTownRanks.json file. It is likely empty or otherwise corrupt. It should generate a new one and your problem should be fixed.
