### ISSUE TITLE
CME exception when using signs

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#383]
It appears there's a multihreading implementation issue when players right click signs:
```
[18:36:18 ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@5a4b64b4:
java.util.ConcurrentModificationException
>       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_85]
>       at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_85]
>       at mytown.entities.signs.SellSign.onRightClick(SellSign.java:70) ~[SellSign.class:?]
>       at myessentials.entities.sign.SignManager.onPlayerInteract(SignManager.java:36) ~[SignManager.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_431_SignManager_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1492.152]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1492.152]
>       at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:1.7.10-1492.152]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) [mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) [nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[18:36:18 ERROR]: Index: 21 Listeners:
[18:36:18 ERROR]: 0: HIGHEST
[18:36:18 ERROR]: 1: ASM: mytown.protection.ProtectionHandlers@51c6fe8d onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 2: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@2ac3ceed vanillaSeedPlanting(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 3: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@2ac3ceed waterPadCreation(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 4: NORMAL
[18:36:18 ERROR]: 5: ASM: binnie.botany.Botany@7d4344af onShearFlower(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 6: ASM: binnie.botany.Botany@7d4344af onFertiliseSoil(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 7: ASM: vazkii.botania.common.block.string.BlockRedStringInterceptor@5ee4a1d5 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 8: ASM: vazkii.botania.common.item.material.ItemManaResource@1d9e300b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 9: ASM: vazkii.botania.common.item.relic.ItemLokiRing@1b28e2cb onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 10: ASM: vazkii.botania.common.item.rod.ItemExchangeRod@745c5054 onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 11: ASM: binnie.core.item.ModuleItems@1339099a onUseFieldKit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 12: ASM: binnie.extratrees.carpentry.BlockCarpentry@46cf86 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 13: ASM: mods.railcraft.common.carts.MinecartHooks@37e14de0 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 14: ASM: team.chisel.item.chisel.ChiselController@130a7de onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 15: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@15c62eb playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 16: ASM: minetweaker.mc1710.ForgeEventHandler@711751be onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 17: ASM: latmod.ftbu.mod.handlers.FTBUPlayerEventHandler@5b5ef221 onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 18: ASM: FLM_ItemWrench@63d10607 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 19: ASM: com.xcompwiz.mystcraft.core.MystcraftEventHandler@69d1868 bottleFix(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 20: ASM: myessentials.entities.tool.ToolManager@453e547e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 21: ASM: myessentials.entities.sign.SignManager@5903dddb onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 22: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@2ac3ceed applyVinesToGrate(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 23: ASM: appeng.parts.PartPlacement@248ab7bd playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 24: ASM: vazkii.botania.common.core.handler.SpawnerChangingHandler@1d7c38b1 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 25: ASM: com.carpentersblocks.util.handler.EventHandler@4416e9bb onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 26: ASM: twilightforest.TFEventListener@1636d314 rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 27: ASM: com.enderio.core.common.handlers.RightClickCropHandler@38ea3623 handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 28: ASM: com.rwtema.extrautils.EventHandlerServer@5187b262 angelBlockDestroy(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 29: ASM: thaumic.tinkerer.common.core.handler.kami.KamiDimensionHandler@1f0c0ad8 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 30: ASM: hunterzcz.ic2laserfix.IC2MiningLaser@19fe3a58 onIC2LaserUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 31: ASM: logisticspipes.LogisticsEventListener@2d6f9473 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 32: ASM: mcjty.rftools.ForgeEventHandlers@a1dfcb1 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 33: ASM: mcjty.rftools.ForgeEventHandlers@a1dfcb1 onPlayerInterractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 34: ASM: stevesaddons.naming.EventHandler@341df4e7 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 35: ASM: com.jaquadro.minecraft.storagedrawers.core.ForgeEventHandler@1c85764b playerInteracts(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 36: ASM: flaxbeard.thaumicexploration.event.TXEventHandler@65f58cd2 handleItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 37: ASM: appeng.fmp.FMPEvent@42287469 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 38: ASM: com.emoniph.witchery.item.ItemPoppet$PoppetEventHooks@21f9ea9c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 39: ASM: com.emoniph.witchery.infusion.Infusion$EventHooks@63b6a540 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 40: ASM: com.emoniph.witchery.common.GenericEvents@5fec4d5e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 41: ASM: com.emoniph.witchery.brewing.DispersalTriggered$EventHooks@764b80f3 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 ERROR]: 42: LOW
[18:36:18 ERROR]: 43: ASM: codechicken.multipart.minecraft.EventHandler@6f36419b playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:36:18 WARN]: Failed to handle packet for /<edited>:42319
java.util.ConcurrentModificationException
>       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_85]
>       at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_85]
>       at mytown.entities.signs.SellSign.onRightClick(SellSign.java:70) ~[SellSign.class:?]
>       at myessentials.entities.sign.SignManager.onPlayerInteract(SignManager.java:36) ~[SignManager.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_431_SignManager_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1492.152]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1492.152]
>       at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1492.152]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) ~[mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) ~[nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[18:36:18 INFO]: LemADEC lost connection: Internal server error
```

This happens with:
MyEssentials-Core-1.7.10-91-dev.jar
MyPermissions-1.7.10-43-dev.jar
MyTown2-1.7.10-289-dev.jar

**Comment by AfterWind** [comment]
Not multithreading, just modifying a list where I shouldn't. We'll fix it.
