### ISSUE TITLE
Server exception kicking player with UndergroundBiomesConstruct

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#395]
With using Underground Biomes Construct, when placing Red granite stairs, an exception happens on server console and client gets kicked. Server doesn't crash per say. Nearby players aren't impacted.

```
[12:47:23] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent@37084330:
java.lang.RuntimeException
        at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.func_149915_a(UBStairsBase.java:58) ~[UBStairsBase.class:?]
        at mytown.protection.ProtectionHandlers.onAnyBlockPlacement(ProtectionHandlers.java:157) ~[ProtectionHandlers.class:?]
        at mytown.protection.ProtectionHandlers.onMultiBlockPlacement(ProtectionHandlers.java:134) ~[ProtectionHandlers.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_139_ProtectionHandlers_onMultiBlockPlacement_MultiPlaceEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1481.148]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerMultiBlockPlace(ForgeEventFactory.java:60) [ForgeEventFactory.class:1.7.10-1481.148]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:593) [ForgeHooks.class:1.7.10-1481.148]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:152) [add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:495) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[12:47:23] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[12:47:23] [Server thread/ERROR] [FML/]: 0: NORMAL
[12:47:23] [Server thread/ERROR] [FML/]: 1: ASM: mytown.protection.ProtectionHandlers@67aa1ac8 onMultiBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$MultiPlaceEvent;)V
[12:47:23] [Server thread/ERROR] [FML/]: 2: ASM: mytown.protection.ProtectionHandlers@67aa1ac8 onBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:47:23] [Server thread/ERROR] [FML/]: 3: ASM: router.reborn.util.ServerEvent@11cbdd9d BlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:47:23] [Server thread/ERROR] [FML/]: 4: ASM: router.reborn.util.ServerEvent@53ad605d BlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:47:23] [Server thread/ERROR] [FML/]: 5: ASM: wtftweaks.util.WTFEventMonitor@60a92b97 PlayerPlaceBlock(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
```

```
[12:48:21] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent@5a666086:
java.lang.RuntimeException
        at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.func_149915_a(UBStairsBase.java:58) ~[UBStairsBase.class:?]
        at mytown.protection.ProtectionHandlers.onAnyBlockPlacement(ProtectionHandlers.java:157) ~[ProtectionHandlers.class:?]
        at mytown.protection.ProtectionHandlers.onMultiBlockPlacement(ProtectionHandlers.java:134) ~[ProtectionHandlers.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_139_ProtectionHandlers_onMultiBlockPlacement_MultiPlaceEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1481.148]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerMultiBlockPlace(ForgeEventFactory.java:60) [ForgeEventFactory.class:1.7.10-1481.148]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:593) [ForgeHooks.class:1.7.10-1481.148]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:152) [add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:495) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[12:48:21] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[12:48:21] [Server thread/ERROR] [FML/]: 0: NORMAL
[12:48:21] [Server thread/ERROR] [FML/]: 1: ASM: mytown.protection.ProtectionHandlers@67aa1ac8 onMultiBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$MultiPlaceEvent;)V
[12:48:21] [Server thread/ERROR] [FML/]: 2: ASM: mytown.protection.ProtectionHandlers@67aa1ac8 onBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:48:21] [Server thread/ERROR] [FML/]: 3: ASM: router.reborn.util.ServerEvent@11cbdd9d BlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:48:21] [Server thread/ERROR] [FML/]: 4: ASM: router.reborn.util.ServerEvent@53ad605d BlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[12:48:21] [Server thread/ERROR] [FML/]: 5: ASM: wtftweaks.util.WTFEventMonitor@60a92b97 PlayerPlaceBlock(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
```

The item is having metadata 24, probably replaced by a tile entity on placement.
No error shows on console when MyTown isn't installed.

Notable mods involved:
KCauldron-1.7.10-1481.148-server.jar
MyEssentials-Core-1.7.10-95-dev.jar
MyPermissions-1.7.10-46-dev.jar
MyTown2-1.7.10-296-dev.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
WTFCaveBiomes-1.7.10_v1.52.jar
WTFCore-1.7.10_v1.65.jar
WTFTweaks-1.7.10_v1.29.jar

**Comment by AfterWind** [comment]
Error caused by UndergroundBiomes. If you find out it is caused by MyTown2 exclusively reopen the issue please.

**Comment by LemADEC** [comment]
As said in original ticket, I can place those block without MyTown2 installed, so yes, issue is in MyTown2.

**Comment by LemADEC** [comment]
Issue is reproduced without WTF mods nor Cauldron:
```
[14:39:07] [Server thread/INFO]: LemADEC joined the game
[14:39:11] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@4be48088:
java.lang.RuntimeException
>       at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.func_149915_a(UBStairsBase.java:58) ~[UBStairsBase.class:?]
>       at mytown.protection.ProtectionHandlers.onAnyBlockPlacement(ProtectionHandlers.java:157) ~[ProtectionHandlers.class:?]
>       at mytown.protection.ProtectionHandlers.onBlockPlacement(ProtectionHandlers.java:129) ~[ProtectionHandlers.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_ProtectionHandlers_onBlockPlacement_PlaceEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
>       at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69) [ForgeEventFactory.class:?]
>       at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535) [ForgeHooks.class:?]
>       at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) [add.class:?]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) [mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) [nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:39:11] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[14:39:11] [Server thread/ERROR] [FML]: 0: NORMAL
[14:39:11] [Server thread/ERROR] [FML]: 1: ASM: mytown.protection.ProtectionHandlers@4e0b05c1 onBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[14:39:11] [Server thread/WARN]: Failed to handle packet for /78.194.44.189:57466
java.lang.RuntimeException
>       at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.func_149915_a(UBStairsBase.java:58) ~[UBStairsBase.class:?]
>       at mytown.protection.ProtectionHandlers.onAnyBlockPlacement(ProtectionHandlers.java:157) ~[ProtectionHandlers.class:?]
>       at mytown.protection.ProtectionHandlers.onBlockPlacement(ProtectionHandlers.java:129) ~[ProtectionHandlers.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_ProtectionHandlers_onBlockPlacement_PlaceEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
>       at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69) ~[ForgeEventFactory.class:?]
>       at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535) ~[ForgeHooks.class:?]
>       at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:39:13] [Server thread/INFO]: LemADEC lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[14:39:13] [Server thread/INFO]: LemADEC left the game
```

forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
MyEssentials-Core-1.7.10-95-dev.jar
MyPermissions-1.7.10-46-dev.jar
MyTown2-1.7.10-296-dev.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar

**Comment by krwminer** [comment]
Um. The mod is being nasty to say the least:

https://github.com/Zeno410/UndergroundBiomesConstructs1.7/blob/master/src/exterminatorJeff/undergroundBiomes/constructs/block/UBStairsBase.java

It declares that UBStairsBase implements a ITileEntityProvider, but declares this gem:

    public TileEntity createNewTileEntity(World world, int i) {
        throw new RuntimeException();
    }


So we look to see if it is a ITileEntityProvider and if so create a TE so we can see if it is one we track. Well, when we create a TE it throws an exception by design. :/

**Comment by AfterWind** [comment]
The issue is not on our side. Ask the mod developer to remove that line and everything will work like normal again.
