### ISSUE TITLE
Exception while adding a block to the whitelist

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#407]
Tested with the last commit: 7dde68cc60c42a998bce70fe83c6b653b6d31068

A successful message is displayed to the player but the block isn't added to the whitelist and this exception is trown:
```
[10:05:36 ERROR]: Failed to save a Block Whitelist!
[10:05:36 ERROR]: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (foreign key constraint failed)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.execute(DB.java:342)
        at org.sqlite.DB.executeUpdate(DB.java:363)
        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
        at mytown.new_datasource.MyTownDatasource.saveBlockWhitelist(MyTownDatasource.java:894)
        at mytown.entities.tools.WhitelisterTool.addWhitelists(WhitelisterTool.java:118)
        at mytown.entities.tools.WhitelisterTool.onItemUse(WhitelisterTool.java:45)
        at myessentials.entities.tool.ToolManager.onPlayerInteract(ToolManager.java:76)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_79_ToolManager_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:423)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)
```

It's being caused because [FlagType](https://github.com/MyEssentials/MyTown2/blob/master/src/main/java/mytown/entities/flag/FlagType.java) lacks `toString()`

**Comment by AfterWind** [comment]
Issue explained on #404
