### ISSUE TITLE
Crash???

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#486]
My server crashes randomly with the same crash:

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:1303)
	at myessentials.chat.api.ChatManager.send(ChatManager.java:30)
	at myessentials.chat.api.ChatManager.send(ChatManager.java:15)
	at mytown.entities.Resident.checkLocationOnDimensionChanged(Resident.java:113)
	at mytown.protection.ProtectionManager.check(ProtectionManager.java:99)
	at mytown.protection.ProtectionHandlers.worldTick(ProtectionHandlers.java:105)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_331_ProtectionHandlers_worldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

**Comment by legobear154** [comment]
Grab MyEssentials-Core build 137 from Jenkins once it's done and let me know if it fixed the problem :)

**Comment by Eufranio** [comment]
Ok, no crashes :D
But why it was happening?
