### ISSUE TITLE
Players teleporting wrong and error when using a blocked command

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#490]
When my players use /town spawn , they are teleported to a wrong place, sometimes even to the void...
So, i blocked the /town spawn putting:

-mytown.cmd.everyone.spawn

in my permission plugin (PermissionsEX). Then, every time they try use /town spawn the console get a lot of flood:

12:23:01 INFO]: joaoespanhol issued server command: /town spawn
[12:23:01 ERROR]: Couldn't process command: 'town spawn'
mytown.util.exceptions.MyTownCommandException
        at mytown.commands.Commands.getTownFromResident(Commands.java:93) ~[Commands.class:?]
        at mytown.commands.RankPermissionManager.hasPermission(RankPermissionManager.java:23) ~[RankPermissionManager.class:?]
        at mypermissions.command.core.entities.CommandTree.hasPermission(CommandTree.java:89) ~[CommandTree.class:?]
        at mypermissions.command.core.entities.CommandTree.commandCall(CommandTree.java:39) ~[CommandTree.class:?]
        at mypermissions.command.core.entities.CommandModel.func_71515_b(CommandModel.java:46) ~[CommandModel.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53) [CraftSimpleCommandMap.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:756) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1377) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

Waiting until the teleport problem be fixed...

**Comment by Eufranio** [comment]
Update: Players are teleported wrong only if they are in a different dimension from the town. 
Example: I have a town in overworld. I use /t spawn, and i'm teleported to the same coordinates of my town, but in the nether.
