### ISSUE TITLE
[BUG] Server crash when validate ranks config!

### ISSUE THREAD

**Issue by nathan130200** [MyEssentials/MyTown2#497]
This is my ranks configs:

[
  {
    "name": "Prefeito",
    "type": "MAYOR",
    "permissions": [
      "mytown.cmd.*",
      "mytown.bypass.*"
    ]
  },
  {
    "name": "Ajudante",
    "type": "REGULAR",
    "permissions": [
      "mytown.cmd*",
      "-mytown.cmd.mayor",
      "mytown.bypass.plot",
      "mytown.bypass.flag.*"
    ]
  },
  {
    "name": "Perdido",
    "type": "REGULAR",
    "permissions": [
      "mytown.cmd.everyone.*",
      "mytown.cmd.outsider.*",
      "-mytown.bypass.flag.*"
    ]
  },
  {
    "name": "Morador",
    "type": "REGULAR",
    "permissions": [
      "mytown.cmd.everyone.*",
      "mytown.cmd.outsider.*",
      "mytown.bypass.flag.*",
      "-mytown.bypass.flag.restrictions"
    ]
  }
]

And crash/exception:

[07:19:58] [Server thread/ERROR]: Caught exception from MyTown2
java.lang.NullPointerException
	at mytown.config.json.RanksConfig.validate(RanksConfig.java:48) ~[RanksConfig.class:?]
	at mytown.config.json.RanksConfig.validate(RanksConfig.java:11) ~[RanksConfig.class:?]
	at myessentials.json.api.JsonConfig.read(JsonConfig.java:99) ~[JsonConfig.class:?]
	at mytown.config.json.RanksConfig.read(RanksConfig.java:33) ~[RanksConfig.class:?]
	at mytown.config.json.RanksConfig.read(RanksConfig.java:11) ~[RanksConfig.class:?]
	at myessentials.json.api.JsonConfig.init(JsonConfig.java:49) ~[JsonConfig.class:?]
	at myessentials.json.api.JsonConfig.init(JsonConfig.java:33) ~[JsonConfig.class:?]
	at mytown.MyTown.serverStarting(MyTown.java:90) ~[MyTown.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-1614.57]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1614.57]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:1.7.10-1614.57]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:282) [FMLCommonHandler.class:1.7.10-1614.57]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:368) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by Eufranio** [comment]
tu tem server?

**Comment by nathan130200** [comment]
Sim via hamachi!
