### ISSUE TITLE
Crash when using Botania method

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#506]
When i try to add a Botania Mana Burst method in a protection, i get this:

```
`java.lang.IllegalAccessError: tried to access method net.minecraft.entity.projectile.EntityThrowable.func_70183_g()F from class vazkii.botania.common.entity.EntityManaBurstMethodAccess
	at vazkii.botania.common.entity.EntityManaBurstMethodAccess.invoke(Unknown Source)
	at mytown.protection.segment.caller.reflectasm.ASMCallerMethod.invoke(ASMCallerMethod.java:18)
	at mytown.protection.segment.getter.GetterDynamic.invoke(GetterDynamic.java:48)
	at mytown.protection.segment.Segment.getOwner(Segment.java:65)
	at mytown.protection.segment.SegmentEntity.shouldExist(SegmentEntity.java:31)
	at mytown.protection.ProtectionManager.checkExist(ProtectionManager.java:129)
	at mytown.protection.ProtectionHandlers.worldTick(ProtectionHandlers.java:109)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_393_ProtectionHandlers_worldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)`
```
My protection:
```
    {
      "class": "vazkii.botania.common.entity.EntityManaBurst",
      "type": "entity",
      "actions": "TRACKED",
      "flags": "MODIFY",
      "owner": [
        {
          "element": "func_70183_g",
          "type": "METHOD"
        }
      ],
      "range": 7
    }
```

**Comment by Eufranio** [comment]
The method is wrong, and I realized I can't protect from Mana Bursts ATM, then... Closing until MyTown2 handles the bursts.
