### ISSUE TITLE
Client crash when doing anything prohibited

### ISSUE THREAD

**Issue by simonappleton** [MyEssentials/MyTown2#99]
My client is crashing when I attempt to break blocks/open doors. I have a new server, an admin town, with block breaking prohibited (I tried doors too). If I attempt to break a block (or open door), my client crashes. The mods are only on the server, not on client.

**Comment by AfterWind** [comment]
Sorry I didn't ask this earlier, but do you have any crash report?

**Comment by mainsheep** [comment]
Have the same problem.

[15:12:13] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@1c315785:
java.lang.NullPointerException
	at mytown.util.Formatter.formatOwnersToString(Formatter.java:228) ~[Formatter.class:?]
	at mytown.util.Formatter.formatOwnerToString(Formatter.java:240) ~[Formatter.class:?]
	at mytown.protection.Protections.onBlockPlacement(Protections.java:268) ~[Protections.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_451_Protections_onBlockPlacement_PlaceEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69) [ForgeEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:595) [ForgeHooks.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:149) [add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:875) [nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[15:12:13] [Server thread/ERROR]: Index: 3 Listeners:
[15:12:13] [Server thread/ERROR]: 0: NORMAL
[15:12:13] [Server thread/ERROR]: 1: ASM: binnie.botany.Botany@16effb78 plantVanilla(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[15:12:13] [Server thread/ERROR]: 2: ASM: thaumcraft.common.lib.events.EventHandlerWorld@1f0b4fb placeBlockEvent(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[15:12:13] [Server thread/ERROR]: 3: ASM: mytown.protection.Protections@6577a7eb onBlockPlacement(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[15:12:13] [Server thread/WARN]: Failed to handle packet for /79.195.118.143:49831
java.lang.NullPointerException
	at mytown.util.Formatter.formatOwnersToString(Formatter.java:228) ~[Formatter.class:?]
	at mytown.util.Formatter.formatOwnerToString(Formatter.java:240) ~[Formatter.class:?]
	at mytown.protection.Protections.onBlockPlacement(Protections.java:268) ~[Protections.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_451_Protections_onBlockPlacement_PlaceEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69) ~[ForgeEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:595) ~[ForgeHooks.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:149) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:875) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[15:12:13] [Server thread/INFO]: Bumsiburger lost connection: Internal server error

**Comment by nylser** [comment]
Is this only happening on Cauldron servers? 
Looks like some part of the owners seems to be null and the format method fails, but I don't necessarily understand the client crash.

**Comment by AfterWind** [comment]
Stop putting MyTown2 on the client. It is only a server mod.

**Comment by evernife** [comment]
Thats true, i have a Cauldron server 1.7.10 Forge Version: 1.1236.05.212 and its working fine.

There is no problem with the mod, just put this on the ServerSide and its done.

AfterWind, i need to ask, in your new version (0.27) there will be a way to do the same as in the MyTown (minecraft 1.6.4). I am talking about of changing the Price Item, actually is the diamond, i tried to change it in the CONFIG, but didn work, will be a way in next version?

(and if is not asking to much, how much time to the next version? ) (sorry for asking redundant things)

**Comment by AfterWind** [comment]
Yup it will work. I have already implemented a way to do it properly and have tested it and it will work. Just wait until I polish some of the things up and you'll have that in the new version.

**Comment by mainsheep** [comment]
I haven't put mytown on the client. The server is running cauldron

**Comment by AfterWind** [comment]
Then make another issue, since it is not the same as your client doesn't crash.
Either way, you don't need to make the issue since the problem here was already fixed.

**Comment by evernife** [comment]
Just to say, if the problem persist, post your  ''server.log'', i think i can take a look.

**Comment by AfterWind** [comment]
I did fix this a few times now xD. Reopen if it occurs again.
